version: "3.8"

services:
  backend:
    build: ./backend
    ports:
      - "9000:9000"
    networks:
      - project-task-network
    environment:
      MONGO_URI: mongodb://mongodb:27017
    depends_on:
      mongodb:
        condition: service_healthy

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    networks:
      - project-task-network
    environment:
      REACT_APP_API_URL: http://backend:9000
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - project-task-network  # Unified network
    volumes:
      - mongo-data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  project-task-network:
    driver: bridge

volumes:
  mongo-data:
    driver: local
